from random import choice
import discord
from discord.ext import commands

class WhichMovieCog(commands.Cog):
    def __init__(self,bot):
        self.bot = bot

    @commands.command()
    async def wichmovie(self,ctx):
        movies = ["Die Reise zur geheimnisvollen Insel",
                  "Die Legende von Aang",
                  "Malibu rescue",
                  "Wolfsnächte",
                  "Bis zum Untergang",
                  "Pfad der Rache",
                  "The Town",
                  "Connected",
                  "Triple Frontier",
                  "The last days of american Crime",
                  "Criminal Squad",
                  "Stolen",
                  "Extingtion",
                  "Burn out",
                  "Snitch",
                  "Wheelman",
                  "Ausnahmezustand",
                  "Inside man",
                  "Looper",
                  "Jack Reacher",
                  "Das Kartell",
                  "Beast stalker",
                  "6 Days",
                  "Force 2",
                  "Shooter",
                  "The italian Job",
                  "I am Legend",
                  "Spectral",
                  "Wold war Z",
                  "Das Bourne Ultimatum",
                  "Inception",
                  "The nice guys",
                  "Players",
                  "The day after tomorrow",
                  "Anacleto",
                  "Oceans eleven",
                  "Ocean's twelve",
                  "Sherlock Holmes",
                  "Das fliegende Auge",
                  "War",
                  "Faster",
                  "211 Cops under fire",
                  "London has fallen",
                  "Hitman",
                  "The hard way",
                  "Wild card"
                  "6 Underground",
                  "Takers",
                  "Spenser",
                  "Tyler Rake extraction",
                  "Escape Plan 1",
                  "Escape Plan 2",
                  "Welcome to the Jungle",
                  "Let's be Cops",
                  "Point break",
                  "Du gegen die Wildnis",
                  "Killer Elite",
                  "Pain and Gain",
                  "Hunter Killer",
                  "Parker",
                  "2 Guns",
                  "Das A-Team",
                  "John Wick",
                  "John Wick 2",
                  "Jack Ryan",
                  "Eagle Eye"
                  "Gods of Egypt",
                  "The Equalizer",
                  "The old Guard",
                  "Sabotage",
                  "The Revenant",
                  "Kampf der Titanen",
                  "Bright",
                  "Rush hour",
                  "Rush hour 2",
                  "Rush hour 3",
                  "Karate Kid",
                  "Karate kid 2",
                  "Ride along",
                  "MIB",
                  "Hancock",
                  "I,Robot",
                  "Sucide Squad",
                  "Aquaman",
                  "Pixels"
                  "Bad Boys",
                  "Bad Boys 2",
                  "Fast and Furious",
                  "Fast and Furious 2",
                  "Fast and Furious 3",
                  "Fast and Furious 4",
                  "Fast and Furious 5",
                  "Fast and Furious 6",
                  "Fast and Furious 7",
                  "The Transporter",
                  "Baby Driver",
                  "Need for Speed",
                  "Finger weg!",
                  "San Andreas",
                  "Pacific Rim",
                  "Transformers",
                  "Transformers 3",
                  "Transformers-The last Knight",
                  "Godzilla"
                  "Godzilla 2",
                  "Hulk",
                  "Man of steel",
                  "Ninja Turtles",
                  "Baywatch",
                  "Wonder Women",
                  "Maze Runner",
                  "Maze Runner 2",
                  "Maze Runner 3",
                  "Iron Man",
                  "Iron Man 2"
                  "Iron Man 3",
                  "Fack ju Göhte",
                  "Fack ju Göhte 2",
                  "Kindsköpfe",
                  "Honig im Kopf",
                  "Shazam",
                  "Deadpool"
                  "Kung Fu Panda",
                  "Kung Fu Panda 2",
                  "Ziemlich beste Freunde",
                  "Kingsman",
                  "Richie Rich",
                  "Ted",
                  "Ted 2",
                  "Bad Moms",
                  "Bad Moms 2",
                  "Charlie und die Schokoladenfabrik",
                  "Hangover",
                  "Hangover 2",
                  "Hangover 3",
                  "Ninja Assassin",
                  "The dark Knight",
                  "Matrix"
                  "Matrix Revolutions",
                  "Matrix Reloadet",
                  "Lucy",
                  "Mission Impossible 4",
                  "Mission Impossible 5"
                  "Terminator 2",
                  "Power Rangers",
                  "Independence Day",
                  "Planet der Affen",
                  "Planet der Affen 2",
                  "Planet der Affen 3",
                  "King Arthur",
                  "Die 5. Welle"]
        movie = choice(movies)
        wichmoviemess = discord.Embed(title="Was soll ich gucken?",
                                      description="Hier ein Vorschlag. " + movie,
                                      color=0x00ffff)
        await ctx.send(embed=wichmoviemess)